(function(){
  const app=document.querySelector('#app');
  if(!app)return;
  let applying=false;
  const names={A:'Public-service directory',B:'Control-center dashboard',C:'Playful tactile interface',D:'Punk-zine collage',E:'One-card-at-a-time wizard',F:'Concierge chat'};

  const cards=()=>[...app.querySelectorAll('.help-card')].map(card=>({card,input:card.querySelector('input'),title:card.querySelector('.help-title')?.textContent.trim()||'',note:card.querySelector('.help-note')?.textContent.trim()||'',icon:card.querySelector('.help-icon')?.textContent.trim()||'•'}));
  const setRadio=(name,value)=>{const i=[...document.querySelectorAll(`[name="${name}"]`)].find(x=>x.value===value);if(i){i.checked=true;i.dispatchEvent(new Event('change',{bubbles:true}));}};
  const clear=()=>app.querySelectorAll('.wizard-deck,.wizard-route,.chat-deck,.chat-route,.chat-plan-intro').forEach(x=>x.remove());
  function labelSwitcher(){const d=document.body.dataset.design||'F';document.querySelector('.layout-lab-note')?.replaceChildren(document.createTextNode(names[d]));document.querySelector('.design-lab-name')?.replaceChildren(document.createTextNode(names[d]));}

  function wizardNeeds(){
    const form=app.querySelector('#needsForm'),grid=form?.querySelector('.help-grid'),items=cards();if(!form||!grid||!items.length)return;
    let index=Math.max(0,items.findIndex(x=>!x.input.checked));if(index<0)index=0;
    const deck=document.createElement('section');deck.className='wizard-deck';grid.before(deck);
    function draw(){const item=items[index],chosen=items.filter(x=>x.input.checked);deck.innerHTML=`<div class="wizard-selected-title">Choice ${index+1} of ${items.length}</div><div class="wizard-card"><div class="wizard-emoji">${item.icon}</div><h2>${item.title}</h2><p>${item.note}</p><button type="button" class="button wizard-toggle ${item.input.checked?'selected':''}">${item.input.checked?'✓ Added':'Add this need'}</button></div><div class="radical-selected">${chosen.length?chosen.map(x=>`<span class="radical-chip">${x.icon} ${x.title}</span>`).join(''):'<span class="radical-chip">Nothing added yet</span>'}</div><div class="wizard-nav"><button type="button" class="button secondary wizard-prev" ${index===0?'disabled':''}>← Previous</button><button type="button" class="button wizard-next">${index===items.length-1?'Continue →':'Next →'}</button></div><p class="error wizard-error" hidden>Please add at least one need.</p>`;
      deck.querySelector('.wizard-toggle').onclick=()=>{item.input.checked=!item.input.checked;item.input.dispatchEvent(new Event('change',{bubbles:true}));draw();};
      deck.querySelector('.wizard-prev').onclick=()=>{if(index){index--;draw();}};
      deck.querySelector('.wizard-next').onclick=()=>{if(index<items.length-1){index++;draw();return;}if(!items.some(x=>x.input.checked)){deck.querySelector('.wizard-error').hidden=false;return;}form.requestSubmit();};
    }draw();
  }

  function wizardRoute(){
    const form=app.querySelector('#routingForm');if(!form)return;const health=Boolean(form.querySelector('[name="medicare"]'));const stages=health?['zip','medicare','medicaid']:['zip'];let pos=0;const ans={zip:form.querySelector('#zip')?.value||'',medicare:form.querySelector('[name="medicare"]:checked')?.value||'',medicaid:form.querySelector('[name="medicaid"]:checked')?.value||''};const box=document.createElement('section');box.className='wizard-route';form.append(box);
    function draw(){const s=stages[pos];if(s==='zip'){box.innerHTML=`<div class="wizard-route-screen"><span class="eyebrow">One thing at a time</span><h2>What is your Illinois ZIP code?</h2><input class="wizard-zip" inputmode="numeric" maxlength="5" value="${ans.zip}" placeholder="60625"><p class="error wizard-route-error" hidden>Enter a valid Illinois ZIP.</p><button type="button" class="button wizard-route-next">${stages.length===1?'Show my plan →':'Next →'}</button><div><button type="button" class="header-button wizard-route-back">← Back</button></div></div>`;box.querySelector('.wizard-route-next').onclick=()=>{const z=box.querySelector('.wizard-zip').value.trim();if(!/^6\d{4}$/.test(z)){box.querySelector('.wizard-route-error').hidden=false;return;}ans.zip=z;form.querySelector('#zip').value=z;if(stages.length===1){form.requestSubmit();return;}pos++;draw();};}else{const q=s==='medicare'?'Do you have Medicare?':'Do you have Medicaid?';box.innerHTML=`<div class="wizard-route-screen"><span class="eyebrow">Question ${pos+1} of ${stages.length}</span><h2>${q}</h2><div class="wizard-route-actions">${['Yes','No','Not sure'].map(v=>`<button type="button" class="button secondary segment-button ${ans[s]===v?'selected':''}" data-value="${v}">${v}</button>`).join('')}</div><button type="button" class="button wizard-route-next" ${ans[s]?'':'disabled'}>${pos===stages.length-1?'Show my plan →':'Next →'}</button><div><button type="button" class="header-button wizard-route-back">← Previous</button></div></div>`;box.querySelectorAll('.segment-button').forEach(b=>b.onclick=()=>{ans[s]=b.dataset.value;setRadio(s,b.dataset.value);box.querySelectorAll('.segment-button').forEach(x=>x.classList.toggle('selected',x===b));box.querySelector('.wizard-route-next').disabled=false;});box.querySelector('.wizard-route-next').onclick=()=>{if(!ans[s])return;if(pos===stages.length-1){form.requestSubmit();return;}pos++;draw();};}box.querySelector('.wizard-route-back').onclick=()=>{if(pos){pos--;draw();}else form.querySelector('#routingBack')?.click();};
    }draw();
  }

  function chatNeeds(){
    const form=app.querySelector('#needsForm'),grid=form?.querySelector('.help-grid'),items=cards();if(!form||!grid||!items.length)return;const deck=document.createElement('section');deck.className='chat-deck';grid.before(deck);
    function draw(){const chosen=items.filter(x=>x.input.checked);deck.innerHTML=`<div class="chat-thread"><div class="chat-bubble"><strong>Hi. What can I help you with?</strong>You can pick more than one.</div>${chosen.length?`<div class="chat-bubble user">I need help with ${chosen.map(x=>x.title).join(', ')}.</div>`:''}<div class="chat-choices">${items.map(x=>`<button type="button" class="chat-choice ${x.input.checked?'selected':''}" data-title="${x.title}">${x.icon} ${x.title}</button>`).join('')}</div><div class="chat-done"><button type="button" class="button chat-continue">${chosen.length?'That’s what I need →':'Choose a topic'}</button></div><p class="error chat-error" hidden>Pick at least one topic.</p></div>`;deck.querySelectorAll('.chat-choice').forEach(b=>b.onclick=()=>{const x=items.find(i=>i.title===b.dataset.title);x.input.checked=!x.input.checked;x.input.dispatchEvent(new Event('change',{bubbles:true}));draw();});deck.querySelector('.chat-continue').onclick=()=>{if(!items.some(x=>x.input.checked)){deck.querySelector('.chat-error').hidden=false;return;}form.requestSubmit();};}draw();
  }

  function chatRoute(){
    const form=app.querySelector('#routingForm');if(!form)return;const health=Boolean(form.querySelector('[name="medicare"]'));const box=document.createElement('section');box.className='chat-route';form.append(box);box.innerHTML=`<div class="chat-thread"><div class="chat-bubble"><strong>What is your Illinois ZIP code?</strong>I’ll use it to find local help.</div><div class="chat-input-row"><input class="chat-zip" inputmode="numeric" maxlength="5" value="${form.querySelector('#zip')?.value||''}" placeholder="60625"></div>${health?`<div class="chat-bubble"><strong>Do you have Medicare?</strong></div><div class="chat-choices chat-medicare">${['Yes','No','Not sure'].map(v=>`<button type="button" class="chat-choice" data-value="${v}">${v}</button>`).join('')}</div><div class="chat-bubble"><strong>Do you have Medicaid?</strong></div><div class="chat-choices chat-medicaid">${['Yes','No','Not sure'].map(v=>`<button type="button" class="chat-choice" data-value="${v}">${v}</button>`).join('')}</div>`:''}<div class="chat-done"><button type="button" class="button chat-show-plan">Show my plan →</button></div><div><button type="button" class="header-button chat-back">← Back</button></div><p class="error chat-route-error" hidden>Enter a valid Illinois ZIP.</p></div>`;
    if(health){[['.chat-medicare','medicare'],['.chat-medicaid','medicaid']].forEach(([sel,name])=>{const cur=form.querySelector(`[name="${name}"]:checked`)?.value||'';box.querySelectorAll(`${sel} .chat-choice`).forEach(b=>{b.classList.toggle('selected',b.dataset.value===cur);b.onclick=()=>{setRadio(name,b.dataset.value);box.querySelectorAll(`${sel} .chat-choice`).forEach(x=>x.classList.toggle('selected',x===b));};});});}
    box.querySelector('.chat-show-plan').onclick=()=>{const z=box.querySelector('.chat-zip').value.trim();if(!/^6\d{4}$/.test(z)){box.querySelector('.chat-route-error').hidden=false;return;}form.querySelector('#zip').value=z;form.requestSubmit();};box.querySelector('.chat-back').onclick=()=>form.querySelector('#routingBack')?.click();
  }

  function chatPlan(){const groups=app.querySelector('.action-plan-groups');if(!groups)return;const active=document.querySelector('.filter.active')?.textContent.trim()||state?.needs?.[0]||'this';groups.insertAdjacentHTML('beforebegin',`<div class="chat-thread chat-plan-intro"><div class="chat-bubble user">Show me ${active.toLowerCase()} help.</div><div class="chat-bubble"><strong>Here’s where I’d start.</strong>I’ll keep the extra options tucked away unless you want them.</div></div>`);}

  function apply(){if(applying)return;applying=true;try{clear();labelSwitcher();const d=document.body.dataset.design||'F',v=document.body.dataset.view||'';if(d==='E'&&v==='needs')wizardNeeds();if(d==='E'&&v==='routing')wizardRoute();if(d==='F'&&v==='needs')chatNeeds();if(d==='F'&&v==='routing')chatRoute();if(d==='F'&&v==='plan')chatPlan();}finally{applying=false;}}

  let scheduled=false;function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(()=>{scheduled=false;apply();});}
  const appObserver=new MutationObserver(mutations=>{const meaningful=mutations.some(m=>[...m.addedNodes,...m.removedNodes].some(n=>n.nodeType===1&&!n.matches?.('.wizard-deck,.wizard-route,.chat-deck,.chat-route,.chat-plan-intro')));if(meaningful)schedule();});
  appObserver.observe(app,{childList:true});
  const bodyObserver=new MutationObserver(schedule);bodyObserver.observe(document.body,{attributes:true,attributeFilter:['data-design','data-view']});
  schedule();
})();
